language: go
go:
  - 1.6.3
  - 1.7rc2
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
    - secure: Tt++Fdp5IqwJyYuK5EFA29BHGInHxVylFQMRtvpNt2qMZA89Z1N4BUDswqVu23TaMwoFM0a1/E3tAuC0Ffqm19oS8jnFyonuFlXduwG8iVb8znWzP67Jtj9l5xDzra/NhdhE25OxUD3b203rOMChpRx77i+eBITlaYsOMUTq/K77at+NW58qL3W7h6vu4WFBG0T0RbEVjp+IxSJiAUJI9jSYYldo7EpeDL/BqMJeMVe1D0UfVa/DU0GNdDKYibmF+Mag/v34ttlfdYarLEicwQpcQb52NfrRg06iPmiiqRsN/glU2clzkJPLZUmx3UgMPK8nKg4Iu8LXKMCm46UhnnsWcXjnquioLa8vPCv2hoModCcwjGLqC4BHnnh4QqNkMnL3UpLWQcT5zrqvsEIcy1TpwKwOEcIRo1ZqEmgl2kkz5hBN6hjFKR44Uti2ayw831X8FRxyGsq7O6b8R7M4w5gdt12Hj2V04Qnr718ZBhsrbNn+GPPv3p9Pspal9CXvuWTnIRbPCw0DOdajLIX9JMUB86ElPqLGxHBsrc6Ev2rsFPlJZqyur9KBU/KJfmlhrV8veksorugMk6nxshzS0P8eAdbmC+xTo999LQPNZqsNVfbKI97UKkfy7jZxHLDriTBD9qHtJSt+J2wkcS6iGrNe5bEpksZAmxJlSwSqIuY=
before_install:
  - make deps
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
install: true
before_script:
  - make
script:
  - make clean
  - make test
  - $HOME/gopath/bin/goveralls -service=travis-ci
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    secure: Lh0JUxPNbJcFgMJ0e9A2BhV4IfT6gntzWsB2g7dvrEYZeKEkTV2AABHKwjPU59bMggaV4js1Qnvt6FSmK2/GmTl64HCSUbuR1qpzuveSeolQNPmUoA71c9q3nOGdC4l1wckvfV8Xwov2NVCukPfHfeN6pi0T6EQF1znLZYihxWFQG0YjN2CsxDJU6vNt4xelY0MMtyHxr0rwp0PJ1z0J/zhkFXe/mbBBsWDayI2XRD+/a2x9QGFVsXRcq9AOFssVAdYL6ZWpRMDnq47nsxFYUDfOk4IMuz09jDKZDqLGrKHAci7WeYdsUHlDU39UFrX3oOLxFWXCqkv7JCaI06bVFgAtEkwUSZXGpCNXKTNnet5aEubU9Ob4d7WWaPL9OhctXlk9pVYXxczPDr+AkFspeA+UcUx9wrzSgUq+xMfPC1Vow1maKEMbrEgv+/2H6gHy09r9LJGBFOQ0VToNJk2l/xHV/1OmcvYxGCneB6q7wGnzoPPFtDk5W0ild5egvVbAqRArqg9ru70uegzkiToFL51dJzbUC5+Z09zeZ4kLtPRIb9s9/Upd4Tq2rJdwQKF2rV0tIDGoioHj6t0GAoC25RrqDq85RE87Un+OO9/LSmOtyVxcabNpTu02xViicT1ZhiddSbQu6rPlBQIeLdr1A6v9JHwJoA10uwHj3f0uSvg=
