version: "{build}"

clone_folder: c:\gopath\src\github.com\performancecopilot\speed

environment:
  GOPATH: c:\gopath
  matrix:
    - environment:
      GOVERSION: 1.10.8
    - environment:
      GOVERSION: 1.11.6
    - environment:
      GOVERSION: 1.12.1

install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=c:\go\bin;%GOPATH%\bin;%PATH%
  - go version
  - go env

build_script:
  - go test -v ./...
